

name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  python-unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./neo/tests.py TestChangedFiles -v




  